name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Python linting and testing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov

      # Lint Python code
      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203

      # Lint Dockerfile with hadolint
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      # Run unit tests
      - name: Run unit tests
        run: |
          pytest --cov=. --cov-report=xml

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

  scorecard:
    runs-on: ubuntu-latest
    permissions:
      # Needed for Scorecard to access repository metadata
      security-events: write
      id-token: write
      contents: read

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Run OpenSSF Scorecard
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          args: >-
            --repo=$GITHUB_REPOSITORY
            --show-details
            --format=json
            --publish-results

      # Upload Scorecard results as an artifact
      - name: Upload Scorecard results
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.json
