name: CI Pipeline

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      # Run Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name my-app my-app:latest

      # Test /version endpoint
      - name: Test /version endpoint
        run: |
          sleep 5 
          response=$(curl --silent http://localhost:8080/version)
          expected_version='{"version":"1.0.0"}'  
          if [ "$response" != "$expected_version" ]; then
            echo "Version mismatch: got $response, expected $expected_version"
            exit 1
          fi
